import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});



const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Todo',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100vh]`}>
				<header></header>
				<main className=' h-full flex justify-center items-center'>
					<div className='w-[600px] flex flex-col border-1 border-slate-500 rounded-md py-[50px] px-[20px] gap-y-10'>{children}</div>
				</main>
				<footer></footer>
			</body>
		</html>
	);
}
